In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import os

In [4]:
path_save = 'datasets/douban'

In [5]:
def read_file(path):
    with open(path, 'r', encoding='latin-1') as f:
        names = f.read().split('\n')[0].split('\t')
    names = [name.replace('"', '') for name in names]
    print(names)
    dtype_names = {name:object for name in names}
    df = pd.read_csv(path, sep = '\t', names = names, dtype = dtype_names, encoding = 'latin-1')
    return df[1:]

In [6]:
df_music = read_file('douban_dataset(text information)/musicreviews_cleaned.txt')

['user_id', 'music_id', 'rating', 'labels', 'comment', 'useful_num', 'time', 'ID']

In [7]:
df_music = df_music[['user_id', 'music_id', 'rating', 'time']]

In [8]:
df_music['item'] = df_music['music_id'].copy()
df_music['user'] = df_music['user_id'].copy()
df_music = df_music.drop(['user_id', 'music_id'], axis = 1)

In [9]:
df_book = read_file('douban_dataset(text information)/bookreviews_cleaned.txt')

['user_id', 'book_id', 'rating', 'labels', 'comment', 'time', 'ID']

In [10]:
df_book = df_book[['user_id', 'book_id', 'rating', 'time']]

In [11]:
df_book['item'] = df_book['book_id'].copy()
df_book['user'] = df_book['user_id'].copy()
df_book = df_book.drop(['user_id', 'book_id'], axis = 1)

In [12]:
df_movie = read_file('douban_dataset(text information)/moviereviews_cleaned.txt')

['user_id', 'movie_id', 'rating', 'comment', 'time', 'labels', 'useful_num', 'CategoryID', 'ID']

In [13]:
df_movie['item'] = df_movie['movie_id'].copy()
df_movie['user'] = df_movie['user_id'].copy()
df_movie = df_movie.drop(['user_id', 'movie_id'], axis = 1)

In [14]:
df_train = pd.concat([df_music, df_book, df_movie])

In [15]:
df_train['timestamp'] = df_train['time'].copy()

In [16]:
df_train['rating'] = df_train['rating'].copy().astype(int)

In [17]:
df_train = df_train[df_train['rating'] >= 3]

In [18]:
df_train

,rating,time,item,user,comment,labels,useful_num,CategoryID,ID,timestamp
1,5,2018-06-29,52381,843,NaN,NaN,NaN,NaN,NaN,2018-06-29
2,3,2018-06-14,52663,843,NaN,NaN,NaN,NaN,NaN,2018-06-14
3,5,2018-06-09,52032,843,NaN,NaN,NaN,NaN,NaN,2018-06-09
4,5,2018-05-16,18446,843,NaN,NaN,NaN,NaN,NaN,2018-05-16
5,5,2018-04-12,5380,843,NaN,NaN,NaN,NaN,NaN,2018-04-12
...,...,...,...,...,...,...,...,...,...,...
1278397,3,2012-09-29,27896,2451,ååï¼å¥½æç±,ç¾å½,,1,1278397,2012-09-29
1278398,5,2012-07-23,48,2451,å¾ç²¾å½©ï¼ç¬å ·å å¿ï¼å¯¹å¤å°å¾·ä¸å¯»å...,çºªå½ç|é³ä¹|å¤å°å¾·|å æ¿å¤§,,1,1278398,2012-07-23
1278399,5,2012-04-05,31594,2451,å½éº»ï¼âæ¿æä½ æ¯æçå èï¼âå°±å...,æ·ç°æ æ¢¨é¦|å æ¿äº®|æ¥å§|SP,,3,1278399,2012-04-05
1278400,4,2012-02-25,30205,2451,å¬äººå¥è¿å,è±å½,,1,1278400,2012-02-25
1278401,4,2010-11-16,29036,2451,ç±æ¯æå¥½çåå«ï¼æå¥½çåå«æ¯æå...,æ¥æ¬|å®«å´èµ|é«è¯å¥å¾|æ¡è°·å¥å¤ª|æ°¸...,,3,1278401,2010-11-16

In [19]:
df_user = read_file('douban_dataset(text information)/users_cleaned.txt')

['user_id', 'living_place', 'join_time', 'self_statement', 'UID']

In [20]:
df_user

,user_id,living_place,join_time,self_statement,UID
1,100274687,ä¸æµ·,2014-09-06,ä¸ä¸ªè¶ çº§ç±ççµå½±çè¿·,1
2,100665563,æ±èåäº¬,2014-09-09,å·²å©äººå¦» å«äºä¸ä¸ªå°è­¦å¯ æ³å »ä¸å...,2
3,1019579,åäº¬,2005-09-04,æ¸¸é¼ã,3
4,102461883,æ¹åæ­¦æ±,2014-09-28,ç¥ç¥ç¥,4
5,103113112,åäº¬,2014-10-11,å¦æææå°±åæé¾ å¯¹ææ¥è¯´çæè°...,5
...,...,...,...,...,...
2714,zwillinge1993,åäº¬,2012-06-18,èªè²è,2714
2715,zxjtmac,ä¸æµ·,2010-07-10,åå²ç³»åºèº«ï¼æ··è¿æ¥ç¤¾ åè¿åºçï¼...,2715
2716,zy0926,å¹¿ä¸ä¸­å±±,2012-08-08,NaN,2716
2717,zykmilan,åäº¬,2009-03-06,æ²¡æä»ä¹è½å¤é»æ¡ï¼ä½ å¯¹èªç±çåå...,2717
2718,Zyy1056114672,éåº,2011-08-04,æææææ¬çå§æ å¥å¹»æ¯æçæç±å¦,2718

In [21]:
df_user['user'] = df_user['UID'].copy()

In [22]:
dict_user_to_id_old = {v:k+1 for k, v in enumerate(df_user['user'].unique())}

In [23]:
df_user['user'] = df_user['user'].copy().map(dict_user_to_id_old)

In [24]:
df_train['user'] = df_train['user'].copy().map(dict_user_to_id_old)

In [25]:
path_save = 'datasets/douban_one_task'

In [26]:
df_train_groupby_item = df_train.groupby('item', as_index = False).agg(lambda x : len(x))

In [27]:
df_train_groupby_item

,item,rating,time,user,comment,labels,useful_num,CategoryID,ID,timestamp
0,1,422,422,422,422,422,422,422,422,422
1,10,205,205,205,205,205,205,205,205,205
2,100,104,104,104,104,104,104,104,104,104
3,1000,17,17,17,17,17,17,17,17,17
4,10000,37,37,37,37,37,37,37,37,37
...,...,...,...,...,...,...,...,...,...,...
94817,9995,44,44,44,44,44,44,44,44,44
94818,9996,45,45,45,45,45,45,45,45,45
94819,9997,31,31,31,31,31,31,31,31,31
94820,9998,57,57,57,57,57,57,57,57,57
94821,9999,48,48,48,48,48,48,48,48,48

In [28]:
df_train_groupby_user = df_train.groupby('user', as_index = False).agg(lambda x : len(x))

In [29]:
#split = 0.95

In [30]:
split = 0.8

In [31]:
df_train_groupby_user['n_interactions'] = df_train_groupby_user['item'].copy()

In [32]:
df_train_groupby_item['n_interactions'] = df_train_groupby_item['user'].copy()

In [33]:
limit_n_of_interactions = 30

In [34]:
list_items_used = df_train_groupby_item['item'][df_train_groupby_item['n_interactions'] > limit_n_of_interactions]

In [35]:
list_items_used.shape

(8349,)

In [36]:
df_train = df_train[df_train['item'].isin(list_items_used)]

In [37]:
dict_item_to_id_old = {v:k+1 for k, v in enumerate(df_train['item'].unique())}

In [38]:
len(dict_item_to_id_old)

8349

In [39]:
df_train['item'] = df_train['item'].map(dict_item_to_id_old)

C:\Users\admin\AppData\Local\Temp\ipykernel_748\1097729408.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_train['item'] = df_train['item'].map(dict_item_to_id_old)

In [40]:
list_users = df_train_groupby_user['user'][np.argsort(-df_train_groupby_user['item'].values)][:int(split * len(df_train_groupby_user))]

In [41]:
list_users_cold_start = df_train_groupby_user['user'][np.argsort(-df_train_groupby_user['item'].values)][int(split * len(df_train_groupby_user)):]

In [42]:
dict_user_to_id = {value : key + 1 for key, value in enumerate(list_users)}

In [43]:
max_user_id = max(list(dict_user_to_id.values()))

In [44]:
dict_user_to_id.update({value : key + 1 + max_user_id for key, value in enumerate(list_users_cold_start)})

In [45]:
list_users = np.arange(list_users.shape[0]) + 1

In [46]:
list_users_cold_start = np.arange(list_users_cold_start.shape[0]) + 1 + max_user_id

In [47]:
df_train['user'] = df_train['user'].map(dict_user_to_id)

C:\Users\admin\AppData\Local\Temp\ipykernel_748\3527280683.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_train['user'] = df_train['user'].map(dict_user_to_id)

In [48]:
df_train['user_item'] = df_train['user'].astype(str) + "|" + df_train['item'].astype(str)

C:\Users\admin\AppData\Local\Temp\ipykernel_748\4199004971.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_train['user_item'] = df_train['user'].astype(str) + "|" + df_train['item'].astype(str)

In [49]:
df_train_groupby_user['n_interactions'] = df_train_groupby_user['item'].copy()
df_train_groupby_user['n_interactions'][df_train_groupby_user['user'].isin(list_users) == False] = 0

In [50]:
split_cold_warm = 0.5

In [51]:
len_new_user = len(list_users_cold_start)

In [52]:
df_test_cold = df_train[df_train['user'].isin(list_users_cold_start[int(split_cold_warm * len_new_user):])]

In [53]:
df_test_warm = df_train[df_train['user'].isin(list_users_cold_start[:int(split_cold_warm * len_new_user)])]

In [54]:
df_train_copy = df_train[df_train['user'].isin(list_users) | df_train['user'].isin(list_users_cold_start[:int(split_cold_warm * len_new_user)])]

In [55]:
df_test_warm = df_test_warm.sort_values(by = ['timestamp']).groupby('user', as_index = False).agg(lambda x : [elem for elem in x][-1])

In [56]:
df_train_copy = df_train_copy[df_train_copy['user_item'].isin(df_test_warm['user_item'].unique()) == False]

In [57]:
df_train = df_train[df_train['user'].isin(list_users)]

In [58]:
split_val = 0.9

In [59]:
df_val = df_train.sort_values(by = ['timestamp']).groupby('user', as_index = False).agg(lambda x : [elem for elem in x][int(split_val * len([elem for elem in x])):])

In [60]:
df_val = df_val.set_index(['user']).apply(pd.Series.explode).reset_index()

In [61]:
df_train = df_train.sort_values(by = ['timestamp']).groupby('user', as_index = False).agg(lambda x : [elem for elem in x][:int(split_val * len([elem for elem in x]))])

In [62]:
df_train = df_train.set_index(['user']).apply(pd.Series.explode).reset_index()

In [63]:
df_train = df_train[df_train['user_item'].isin(df_val['user_item'].unique()) == False]

In [64]:
df_train_groupby_user['n_interactions'] = df_train_groupby_user['item'].copy()
df_train_groupby_user['n_interactions'][df_train_groupby_user['user'].isin(list_users) == False] = 0

In [65]:
df_val = df_train.sort_values(by = ['timestamp']).groupby('user', as_index = False).agg(lambda x : [elem for elem in x][-2])

In [66]:
df_train = df_train[df_train['user_item'].isin(df_val['user_item'].unique()) == False]

In [67]:
df_test = df_train.sort_values(by = ['timestamp']).groupby('user', as_index = False).agg(lambda x : [elem for elem in x][-1])

In [68]:
df_train = df_train[df_train['user_item'].isin(df_test['user_item'].unique()) == False]

In [69]:
def save_txt(data, filename):
    data_groupby_users = data.groupby("user", as_index = False).agg(lambda x : " ".join([str(elem) for elem in x]))
    data_groupby_users = data_groupby_users.sort_values(by = ["user"])
    final_data = data_groupby_users["user"].apply(lambda x : str(x) + "|") + data_groupby_users["item"]
    final_data = final_data.values
    final_data = "\n".join(final_data)
    f = open(filename, "w")
    f.write(final_data)
    f.close()
    print("Done")

In [70]:
save_txt(df_train, path_save + "/train_for_test.txt")

Done

In [71]:
df_train.groupby('user', as_index = False).agg(lambda x : len(x))['item'].min()

9

In [72]:
save_txt(df_test_cold, path_save + "/test_cold.txt")

Done

In [73]:
save_txt(df_test_warm, path_save + "/test_warm.txt")

Done

In [74]:
save_txt(df_train, path_save + "/train.txt")

Done

In [75]:
save_txt(df_val, path_save + "/val.txt")

Done

In [76]:
save_txt(df_test, path_save + "/test.txt")

Done

In [77]:
if False:    
    #df_train_copy = df_train.copy()
    #data_copy = data_copy[data_copy["task_id"] == 0]
    #save_kg_txt = df_train_copy["user"].apply(lambda x : str(x) + " ") + df_train_copy['rating'].astype(str) + df_train_copy["item"].apply(lambda x : " " + str(x))
    save_kg_txt = df_train_copy["user"].apply(lambda x : str(x) + " ") + "0" + df_train_copy["item"].apply(lambda x : " " + str(x))
    save_kg_txt = "\n".join(save_kg_txt.values)

In [78]:
if True:    
    #df_train_copy = df_train.copy()
    #data_copy = data_copy[data_copy["task_id"] == 0]
    #save_kg_txt = df_train_copy["user"].apply(lambda x : str(x) + " ") + df_train_copy['rating'].astype(str) + df_train_copy["item"].apply(lambda x : " " + str(x))
    #df_train_copy['rating'][df_train_copy['rating'] < 3] = 0
    #df_train_copy['rating'][df_train_copy['rating'] >= 3] = 1
    save_kg_txt = df_train_copy["user"].apply(lambda x : str(x) + " ") + df_train_copy['rating'].astype(int).astype(str) + df_train_copy["item"].apply(lambda x : " " + str(x))
    save_kg_txt = "\n".join(save_kg_txt.values)

In [79]:
df_train_copy

,rating,time,item,user,comment,labels,useful_num,CategoryID,ID,timestamp,user_item
4,5,2018-05-16,1,271,NaN,NaN,NaN,NaN,NaN,2018-05-16,271|1
13,5,2018-03-07,2,271,NaN,NaN,NaN,NaN,NaN,2018-03-07,271|2
14,3,2018-03-05,3,271,NaN,NaN,NaN,NaN,NaN,2018-03-05,271|3
15,4,2018-03-05,4,271,NaN,NaN,NaN,NaN,NaN,2018-03-05,271|4
16,5,2018-03-04,5,271,NaN,NaN,NaN,NaN,NaN,2018-03-04,271|5
...,...,...,...,...,...,...,...,...,...,...,...
1278395,3,2012-11-04,2209,2006,ç æµ·æºåºå¤§å·´ä¸çç,,,1,1278395,2012-11-04,2006|2209
1278396,4,2012-10-04,1257,2006,å­1æ¬¡ãåæ°¸å°ç¾ååç¬ç¦äº­é¹¤ç¶æ¼...,æ¥æ¬|å±±ç°æ´æ¬¡|åæ°¸å°ç¾å|ç¬ç¦äº­é...,,3,1278396,2012-10-04,2006|1257
1278399,5,2012-04-05,5548,2006,å½éº»ï¼âæ¿æä½ æ¯æçå èï¼âå°±å...,æ·ç°æ æ¢¨é¦|å æ¿äº®|æ¥å§|SP,,3,1278399,2012-04-05,2006|5548
1278400,4,2012-02-25,7958,2006,å¬äººå¥è¿å,è±å½,,1,1278400,2012-02-25,2006|7958
1278401,4,2010-11-16,4779,2006,ç±æ¯æå¥½çåå«ï¼æå¥½çåå«æ¯æå...,æ¥æ¬|å®«å´èµ|é«è¯å¥å¾|æ¡è°·å¥å¤ª|æ°¸...,,3,1278401,2010-11-16,2006|4779

In [80]:
save_kg_txt.split('\n')[0]

'271 5 1'

In [81]:
df_train['user'].nunique()

2171

In [82]:
f = open(path_save + "/kg_final.txt", "w")
f.write(save_kg_txt)
f.close()

In [83]:
check = False

In [84]:
categorical_user_columns = ['categories']

In [85]:
df_user['categories'] = df_user['living_place'].astype(str)

In [86]:
df_user['user'] = df_user['user'].map(dict_user_to_id)

In [87]:
df_train_groupby_user = df_train.groupby('user', as_index = False).agg(lambda x : len(x))

In [88]:
df_train_groupby_user['n_interactions'] = df_train['item'].copy()

In [89]:
user_to_n_interactions = dict(df_train_groupby_user[['user', 'n_interactions']].values)

In [90]:
df_user['n_interactions'] = df_user['user'].map(user_to_n_interactions)
df_user['n_interactions'][pd.isnull(df_user['n_interactions'])] = 0

C:\Users\admin\AppData\Local\Temp\ipykernel_748\630573040.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_user['n_interactions'][pd.isnull(df_user['n_interactions'])] = 0

In [91]:
numeric_user_columns = ['n_interactions']

In [92]:
with open(path_save + '/user_numeric_name_columns.txt', 'w') as f:
  f.write('\t'.join(numeric_user_columns))
  f.close()

In [93]:
with open(path_save + '/user_category_name_columns.txt', 'w') as f:
  f.write('\t'.join(categorical_user_columns))
  f.close()

In [94]:
with open(path_save + '/item_numeric_name_columns.txt', 'w') as f:
  f.write('\t'.join([]))
  f.close()

In [95]:
with open(path_save + '/item_category_name_columns.txt', 'w') as f:
  f.write('\t'.join([]))
  f.close()

In [96]:
def preprocessing_categories_id(data, column, begin_index, all_category_keys = None):    
    if all_category_keys is None: 
        all_category_ids = data[column][pd.isnull(data[column]) == False].apply(lambda x : str(x) + ",").sum()
        all_category_ids = str(all_category_ids)[:-1]
        all_category_ids = list(set(all_category_ids.split(",")))
        try:
            all_category_ids = np.sort(np.asarray(all_category_ids).astype(int))
        except:
            all_category_ids = np.asarray(all_category_ids)
        all_category_ids = all_category_ids.astype(str)
        new_category_ids = np.linspace(0, all_category_ids.shape[0] - 1, all_category_ids.shape[0]).astype(int).reshape(-1, 1) + begin_index
        all_category_keys = dict(np.hstack((all_category_ids.reshape(-1, 1), new_category_ids)))
        new_begin_index = np.max(new_category_ids[:, 0]) + 1
    else:
        new_begin_index = max(list(all_category_keys.values())) + 1
    data[column][pd.isnull(data[column]) == False] = data[column][pd.isnull(data[column]) == False].apply(lambda x : "\t".join([str(all_category_keys[elem]) for elem in str(x).split(",")])  + "\t")

    data[column][pd.isnull(data[column])] = "0"
    
    return all_category_keys, data, new_begin_index

In [97]:
begin_index = 0

In [98]:
for column in categorical_user_columns:
    if True:
        category_keys, df_user, begin_index = preprocessing_categories_id(df_user, column, begin_index)

C:\Users\admin\AppData\Local\Temp\ipykernel_748\1012888985.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[column][pd.isnull(data[column]) == False] = data[column][pd.isnull(data[column]) == False].apply(lambda x : "\t".join([str(all_category_keys[elem]) for elem in str(x).split(",")])  + "\t")
C:\Users\admin\AppData\Local\Temp\ipykernel_748\1012888985.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[column][pd.isnull(data[column])] = "0"

In [99]:
df_user["all_categories"] = df_user[categorical_user_columns].sum(axis = 1)
df_user["all_categories"] = df_user["all_categories"].apply(lambda x : x[:-1])

In [100]:
df_user["all_categories"]

1       310
2        51
3       348
4       224
5       348
       ...
2714    348
2715    310
2716    184
2717    348
2718     67
Name: all_categories, Length: 2718, dtype: object

In [101]:
df_user.to_csv(path_save + '/user_features.csv', index = False)

In [102]:
#!python main_kgat_2.py --data_name ml_1m_one_task --use_pretrain 0 --cf_print_every 16 --kg_print_every 16 --evaluate_every 1 --Ks '[20, 50]' --cf_batch_size 1024  --lr 1e-4 --masking_train 1 --use_weight_embeds 1 --training_embed_weight 1 --use_train_data_to_train_weight_embed 1 --use_weight_embeds_no_grad 1

In [103]:
#!python main_kgat_2.py --data_name ml_1m_one_task --use_pretrain 0 --cf_print_every 16 --kg_print_every 16 --evaluate_every 1 --Ks '[20, 50]' --cf_batch_size 1024  --lr 1e-3 --masking_train 1 --use_weight_embeds 1 --training_embed_weight 1 --use_train_data_to_train_weight_embed 1 --full_sampling 1

In [104]:
#!python main_kgat_2.py --data_name ml_1m_one_task --use_pretrain 0 --cf_print_every 16 --kg_print_every 16 --evaluate_every 1 --Ks '[20, 50]' --cf_batch_size 1024  --lr 1e-2 --masking_train 1 --use_weight_embeds 1 --training_embed_weight 1 --use_train_data_to_train_weight_embed 0 --full_sampling 1

In [105]:
#!python main_kgat_2.py --data_name ml_1m_one_task --use_pretrain 0 --cf_print_every 16 --kg_print_every 16 --evaluate_every 1 --Ks '[20, 50]' --cf_batch_size 1024  --lr 1e-2 --masking_train 1 --use_weight_embeds 1 --training_embed_weight 0 --use_train_data_to_train_weight_embed 0 --full_sampling 1

In [106]:
#!python main_kgat_2.py --data_name ml_1m_one_task --use_pretrain 0 --cf_print_every 16 --kg_print_every 16 --evaluate_every 1 --Ks '[20, 50]' --cf_batch_size 1024  --lr 1e-2 --masking_train 1 --use_weight_embeds 0 --training_embed_weight 0 --use_train_data_to_train_weight_embed 0 --full_sampling 1

In [107]:
#!python main_kgat_raw.py --data_name ml_1m_one_task --use_pretrain 0 --cf_print_every 16 --kg_print_every 16 --evaluate_every 1 --Ks '[20, 50]' --cf_batch_size 1024  --lr 1e-2 --masking_train 1